nameChanges
Prathin67/college-exhi pull request #1
Opened 2022-12-08 10:55 UTC by Prathin67

2022-12-08 11:02 UTC, Sushmitha-Vk requested changes

2022-12-08 11:02 UTC, Sushmitha-Vk commented on src/app/add/add.component.ts
> +    this.serv.createELEMENT({...data,id:data['slno']}).subscribe(detail =>{
detail is not used inside subscribe so dont declare it

2022-12-08 11:02 UTC, Sushmitha-Vk commented on src/app/card/card.component.ts
>      dialogRef.afterClosed().subscribe(result=>{
same as above comment

2022-12-08 11:36 UTC, Sushmitha-Vk requested changes

2022-12-08 11:36 UTC, Sushmitha-Vk commented on src/app/add/add.component.ts
> +    window.location.reload();
this is wrong, `window.location.reload(); ` should be inside subscribe only. I just said to remove the value declaration

2022-12-08 11:36 UTC, Sushmitha-Vk commented on src/app/card/card.component.ts
> +    dialogRef.afterClosed().subscribe({
why is empty {} used here

2022-12-08 11:36 UTC, Sushmitha-Vk commented on src/app/menu-cmp/menu-cmp.component.ts
> +    window.location.reload()
same as above

2022-12-12 06:13 UTC, Prathin67 commented on src/app/card/card.component.ts
> +    dialogRef.afterClosed().subscribe({
resolved

2022-12-13 06:12 UTC, Sushmitha-Vk approved these changes

2022-12-13 06:13 UTC, merged